### PR TITLE
multiple additions

### PR DESCRIPTION
**Pull request by jonomango**
Added:
* INVPCID types and descriptor.
* Pending Debug Exceptions structure.
* 64-bit Interrupt Gate Descriptor structure.
* 64-bit Task State Segment structure.
* XCR0 structure.
* CPUID 0x80000008 (was already in ia32-doc, but wasn't included for some reason).
* Added some fields to CR4.
* Fixed MTRR PHYSMASK structure (removed Type field).
* Updated the EPTP structure (added Enable Supervisor Shadow Stack Pages field).

Note:
None of these commits will break any code that is currently using ia32-doc (as far as I'm aware). The first 2 commits have already been merged but apparently I don't know how to use GitHub so they're gonna be merged again, not too sure what's up with that.

### CODE REVIEW

**Comment by tandasat** [comment]
@jonomango I too notice the repo has not been active for merging PRs. If you like, you could work with my clone so we do not duplicate work. Mine has multiple fixes and additions such as HALT, CET and VT-d related definitions. 
https://github.com/tandasat/ia32-doc/commits/master

**Comment by jonomango** [comment]
@tandasat Yeah I saw your PR a couple of months ago but was hoping that the original author would be back by now. I'll try to move my fork over to yours, although I'm a git noob so this might take a while lol.

**Comment by wbenny** [comment]
Hi there, sorry guys to disappoint you. Kinda going through personal issues and burn out.

I registered an `ia32-doc` organisation. What do you say if I transfered my repo there and added you as members? Would you be interested?

**Comment by tandasat** [comment]
No worries, a hobby project is a hobby. Please care of yourself @wbenny. 

Transferring to the org sounds a great idea. I would be happy to contribute to and maintain this wonderful project there.

**Comment by jonomango** [comment]
@wbenny Don't worry about it. Burnout happens to the best of us. I'm just glad that this project exists in the first place, it's really saved me a lot of time and I'm sure many others feel the same way.

I'm not really sure how a GitHub organization works in the first place, but as long as I can submit PRs to somewhere and have them looked over, then I'd be happy to contribute as well.

**Pull request closed without merging**
